### ISSUE TITLE
Embeddings returing empty

### ISSUE THREAD

**Issue by anjaneyulu1987** [saxenaakansha30/drupal-rag-app#2]
1)Enabled the Drupal rag custom module
2)added the content in article content type
3)Tried to access the FastAPI url for fetching all the docs(http://192.168.0.102:8000/all-docs)
its returning below response with empty in embeddings. Why the embedding are empty?

{
  "Collection_count": {
    "ids": [
      "nid_10044_1",
      "nid_10045_1",
      "nid_10045_2"
    ],
    "embeddings": null,
    "documents": [
      "<h3>Species:</h3><ul><li>There are three main species of elephants:<ul><li><strong>African Savanna Elephant</strong></li></ul>",
      "<p>The concept of a \"beautiful girl\" can vary widely depending on cultural, personal, and subjective perspectives.",
      "interactions with others.</li><li><strong>Style and Presentation</strong>:"
    ],
    "uris": null,
    "data": null,
    "metadatas": [
      null,
      null,
      null
    ],
    "included": [
      "documents",
      "metadatas"
    ]
  }
}

**Comment by saxenaakansha30** [comment]
@anjaneyulu1987: 

Can you please do the following steps to make sure your set-up is working.

1. Run Ollama.
2. Go to your FastAPI backend and access /docs.
3. Use the /feed/add API to add any random information about yourself that we can use to test if RAG works.
4. Use the /ask API to test by asking, "Hey, who is <YOUR_NAME>?"
5. If the response includes information about you, the RAG backend app works perfectly fine.

Please use this video, I have recorded all the steps that will guide you:

[rag-issue-working.webm](https://github.com/user-attachments/assets/a8417940-2f80-4200-9094-db8a0429f30d)

Coming back to your question:
In ChromaDB, embeddings are typically managed internally and are not exposed through the API unless explicitly requested.

**Comment by saxenaakansha30** [comment]
I have also updated the Read.MD with required packages for the project. The list might also help with a working set-up.

**Comment by AnjaneyuluNTR** [comment]
@saxenaakansha30 Thank you. It works.
